version: "2"
volumes:
  prometheus_diff_data:
services:
  provider:
    image: camptocamp/terraform-diff-prometheus
    build: provider/
    volumes:
      - prometheus_diff_data:/data/
  webserver:
    image: httpd
    ports:
      - "8080:80"
    labels:
      prometheus_port: 8080
    volumes:
      - prometheus_diff_data:/usr/local/apache2/htdocs/

